# Generated by Django 6.0.3 on 2026-04-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navcate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='链接')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
            ],
            options={
                'verbose_name': '导航栏',
                'verbose_name_plural': '导航栏',
                'db_table': 'nav_cate',
            },
        ),
    ]
