# Generated by Django 6.0.3 on 2026-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0002_navcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='upload/banner/', verbose_name='图片')),
                ('url', models.CharField(max_length=200, verbose_name='跳转链接')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '焦点图表',
                'verbose_name_plural': '焦点图表',
                'db_table': 'banner',
            },
        ),
    ]
