# Generated by Django 6.0.3 on 2026-04-23 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('image', models.ImageField(upload_to='upload/tag/', verbose_name='图片')),
                ('description', models.CharField(max_length=200, verbose_name='介绍')),
                ('is_recommend', models.BooleanField(default=True, verbose_name='是否首页推荐')),
                ('is_online', models.BooleanField(default=True, verbose_name='是否上线')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.IntegerField(default=0, verbose_name='顶级分类'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('image', models.ImageField(upload_to='upload/course/', verbose_name='图片')),
                ('description', models.CharField(max_length=200, verbose_name='课程简介')),
                ('level', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='级别')),
                ('studentCount', models.IntegerField(default=0, verbose_name='销量')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('discount', models.FloatField(default=0.0, verbose_name='优惠价格')),
                ('top_category', models.IntegerField(default=0, verbose_name='顶级分类')),
                ('floor', models.IntegerField(default=0, verbose_name='楼层')),
                ('is_recommend', models.BooleanField(default=True, verbose_name='是否首页推荐')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcourse.category', verbose_name='所属分类')),
                ('tags', models.ManyToManyField(related_name='courses', to='tcourse.tags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
                'db_table': 'courses',
            },
        ),
    ]
