# Generated by Django 6.0.3 on 2026-04-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0004_tags_category_floor_category_top_category_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('avatar', models.ImageField(upload_to='upload/teacher/', verbose_name='图片')),
                ('role', models.IntegerField(choices=[(0, '讲师'), (1, '导师'), (2, '班主任')], default=0, verbose_name='角色')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(max_length=50, verbose_name='职称')),
                ('description', models.CharField(max_length=200, verbose_name='介绍')),
            ],
            options={
                'verbose_name': '讲师表',
                'verbose_name_plural': '讲师表',
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='课程附件路径'),
        ),
        migrations.AddField(
            model_name='courses',
            name='audience',
            field=models.TextField(blank=True, null=True, verbose_name='适合人群'),
        ),
        migrations.AddField(
            model_name='courses',
            name='click_count',
            field=models.IntegerField(default=10, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='courses',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='课程介绍'),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='课程付费类型'),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons',
            field=models.IntegerField(default=0, verbose_name='课程课时数'),
        ),
        migrations.AddField(
            model_name='courses',
            name='outcomes',
            field=models.TextField(blank=True, null=True, verbose_name='课程收获'),
        ),
        migrations.AddField(
            model_name='courses',
            name='pub_lessons',
            field=models.IntegerField(default=0, verbose_name='课程已更新课时数'),
        ),
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.IntegerField(choices=[(0, '预上线'), (1, '上线'), (2, '下线')], default=1, verbose_name='课程状态'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='studentCount',
            field=models.IntegerField(default=0, verbose_name='课程学习人数'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('number', models.IntegerField(default=1, verbose_name='章节序号')),
                ('summary', models.CharField(max_length=200, verbose_name='章节简介')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='tcourse.courses', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章表',
                'verbose_name_plural': '章表',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('orders', models.IntegerField(default=1, verbose_name='节序号')),
                ('duration', models.IntegerField(default=0, verbose_name='时长')),
                ('link', models.CharField(max_length=200, verbose_name='视频地址')),
                ('is_free_trial', models.BooleanField(default=False, verbose_name='是否免费')),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='tcourse.chapter', verbose_name='章')),
            ],
            options={
                'verbose_name': '节表',
                'verbose_name_plural': '节表',
                'db_table': 'lesson',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tcourse.teacher', verbose_name='讲师'),
        ),
    ]
