# Generated by Django 6.0.3 on 2026-05-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0005_teacher_courses_attachment_path_courses_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('types', models.IntegerField(default=1, verbose_name='价格类型')),
                ('name', models.CharField(max_length=50, verbose_name='价格名称')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='价格')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tcourse.courses')),
            ],
            options={
                'verbose_name': '课程价格表',
                'verbose_name_plural': '课程价格表',
                'db_table': 'course_price',
            },
        ),
    ]
