# Generated by Django 5.2.12 on 2026-05-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0007_courseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('full', models.IntegerField(default=0, verbose_name='满金额')),
                ('minus', models.IntegerField(default=0, verbose_name='减金额')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('status', models.IntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已评价'), (4, '已完成'), (5, '已取消')], default=1, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='订单总金额')),
                ('payment_method', models.IntegerField(default=0, verbose_name='支付方式')),
                ('is_use_coupon', models.BooleanField(default=False, verbose_name='是否使用优惠券')),
                ('coupon_number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='优惠券编号')),
                ('coupon_amount', models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='优惠金额')),
                ('actual_payment', models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='实际支付金额')),
                ('transaction_no', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='流水号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'user_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('course', models.IntegerField(verbose_name='课程id')),
                ('price', models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='价格')),
                ('introduction', models.CharField(default='', max_length=200, verbose_name='课程介绍')),
                ('valid_type', models.IntegerField(default=0, verbose_name='有效期类型')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tcourse.userorder', to_field='order_number', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'order_detail',
            },
        ),
    ]
