# Generated by Django 6.0.3 on 2026-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0008_coupon_userorder_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='total_comments',
            field=models.IntegerField(default=0, verbose_name='总评价数'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已评价'), (4, '已完成'), (5, '已取消'), (6, '退款中'), (7, '已退款')], default=1, verbose_name='订单状态'),
        ),
    ]
