# Generated by Django 6.0.3 on 2026-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcourse', '0010_rename_is_free_trail_lesson_is_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='courseprice',
            name='types',
            field=models.IntegerField(choices=[(1, '永久有效'), (2, '一个月'), (3, '一年'), (4, '2年')], default=1, verbose_name='价格类型'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
    ]
