"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.version_info = (2, 3, 0, "final", 0)
pymysql.install_as_MySQLdb()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eh3^h(k0b7zg78jyrkg$ed7zf0u(4at=@gg8sk_6=x(nt+&=y@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',  # Django Channels ASGI 服务器，需置于首位以接管 runserver
    'channels',  # WebSocket 实时通信支持
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "corsheaders",
    'euser',
    'tcourse',
    'live',  # 新增：直播互动应用
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'middleware.jwt_middleware.JWTAuthenticationMiddleware'
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ASGI 应用入口（Django Channels WebSocket 必需）
ASGI_APPLICATION = 'myproject.asgi.application'

# Channels 通道层配置：使用 Redis 后端支持多进程/多 Worker 分布式部署
# 跨进程通信：弹幕广播、在线人数同步；生产环境可指定独立 Redis 实例
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    }
}

# Redis 缓存：用于直播间在线人数计数、弹幕持久化（Redis Streams）、限流
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "edupro",
        'USER': "root",
        'PASSWORD':'root',
        'HOST':"localhost",
        'PORT':3306,
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# 1. 基础路径配置（确保根目录正确）
import os
from pathlib import Path

# 项目根目录（manage.py 所在目录）
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 2. 媒体文件核心配置
# 访问URL前缀：http://127.0.0.1:8000/upload/upload/course/88.png
MEDIA_URL = '/upload/'
# 本地存储路径：static/upload (upload_to会再拼接一层upload/course/)
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'upload')

# 3. 静态文件基础配置（确保static目录被识别）
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 把根目录的static加入静态文件搜索路径
]

# 4. 确保DEBUG=True（开发环境必须开启，否则静态/媒体文件不生效）
DEBUG = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os,datetime
# 日志配置字典，用于配置Django项目的日志记录系统
# 包含日志格式化器、过滤器、处理器和记录器的完整配置
LOG_PATH = BASE_DIR / "logs"
if not os.path.exists(LOG_PATH):
    os.makedirs(LOG_PATH)

    # 日志配置
LOGGING = {
    'version': 1,  # 指定日志配置版本号
    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器

    # 定义日志格式化器，用于控制日志输出的格式
    'formatters': {
        'verbose': {  # 详细格式，包含更多调试信息
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {  # 简单格式，适用于一般日志记录
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d][%(message)s]',
        },
    },

    # 定义日志过滤器，用于控制日志的输出条件
    'filters': {
        'require_debug_true': {  # 只在Django调试模式下输出日志的过滤器
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    # 定义日志处理器，用于指定日志的输出目标和方式
    'handlers': {
        'console': {  # 控制台输出处理器，用于开发调试
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {  # 文件输出处理器，将日志写入文件并按大小轮转
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / f'code_env_space_{datetime.datetime.now().strftime("%Y-%m-%d")}.log'),
            'maxBytes': 300 * 1024 * 1024,  # 单个日志文件最大300MB
            'backupCount': 10,  # 最多保留10个历史日志文件
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
        'error': {  # 错误日志处理器，专门记录错误级别以上的日志
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / f'error_{datetime.datetime.now().strftime("%Y-%m-%d")}.log'),
            'maxBytes': 300 * 1024 * 1024,  # 单个日志文件最大300MB
            'backupCount': 10,  # 最多保留10个历史错误日志文件
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
        'celery': {  # Celery任务队列日志处理器
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / f'celery_{datetime.datetime.now().strftime("%Y-%m-%d")}.log'),
            'maxBytes': 300 * 1024 * 1024,  # 单个日志文件最大300MB
            'backupCount': 10,  # 最多保留10个历史Celery日志文件
            'formatter': 'verbose',
            'encoding': 'utf-8'
        },
    },

    # 定义日志记录器，用于指定不同模块使用哪些处理器记录日志
    'loggers': {
        'django': {  # Django框架相关日志记录器
            'handlers': ['console', 'file', 'error'],
            'propagate': True,
            'level': 'INFO',
        },
        'django.db.backends': {  # 数据库相关日志记录器
            'handlers': ['console', 'file', 'error'],
            'propagate': True,
            'level': 'INFO',
        },
        'apps': {  # 自定义应用日志记录器
            'handlers': ['console', 'file', 'error'],
            'propagate': True,
            'level': 'INFO',
        },
        'celery': {  # Celery任务队列日志记录器
            'handlers': ['celery', 'console', 'error'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}


# 邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 发件人邮箱服务器
# QQ邮箱
EMAIL_HOST = 'smtp.qq.com'
# 163邮箱：EMAIL_HOST = 'smtp.163.com'

# 发件人邮箱
EMAIL_HOST_USER = '1589512739@qq.com'

# 邮箱授权码（不是登录密码！）
EMAIL_HOST_PASSWORD = 'amuawtpwasidhfbj'

# 端口
EMAIL_PORT = 465  # QQ/163 通用SSL端口

# 使用SSL加密
EMAIL_USE_SSL = True

# 默认发件人名称
DEFAULT_FROM_EMAIL = '艾瑞斯<1589512739@qq.com>'
