# Generated by Django 6.0.3 on 2026-05-11 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euser', '0002_user_delete_tuers'),
        ('tcourse', '0008_coupon_userorder_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('course_type', models.IntegerField(choices=[(1, '永久有效'), (2, '一个月'), (3, '一年'), (4, '2年')], default=1, verbose_name='课程类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('status', models.IntegerField(choices=[(1, '未开始'), (2, '学习中'), (3, '已完成')], default=1, verbose_name='状态')),
                ('total_time', models.IntegerField(default=0, verbose_name='学习总时长')),
                ('progress', models.IntegerField(default=0, verbose_name='学习进度')),
                ('is_favor', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcourse.courses', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '我的课程',
                'verbose_name_plural': '我的课程',
                'db_table': 'my_course',
            },
        ),
    ]
