# Generated by Django 6.0.3 on 2026-05-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euser', '0003_mycourse'),
        ('tcourse', '0010_rename_is_free_trail_lesson_is_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='status',
            field=models.IntegerField(choices=[(1, '未开始'), (2, '学习中'), (3, '已完成'), (4, '已退款')], default=1, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('star', models.IntegerField(default=5, verbose_name='星级')),
                ('avatar', models.CharField(blank=True, max_length=300, null=True, verbose_name='头像')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tcourse.courses', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'comment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order_no', models.CharField(max_length=100, verbose_name='订单号')),
                ('alipay_number', models.CharField(max_length=100, verbose_name='支付宝流水号')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '已同意'), (2, '已拒绝'), (3, '已完成')], default=0, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '申请退款记录',
                'verbose_name_plural': '申请退款记录',
                'db_table': 'refund',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('approver', models.CharField(max_length=32, verbose_name='审批人')),
                ('approve_time', models.DateTimeField(verbose_name='审批时间')),
                ('status', models.IntegerField(choices=[(1, '同意'), (2, '不同意')], default=1, verbose_name='状态')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_process', to='euser.refund', verbose_name='申请退款记录')),
            ],
            options={
                'verbose_name': '售后流程记录',
                'verbose_name_plural': '售后流程记录',
                'db_table': 'refund_process',
                'ordering': ['-id'],
            },
        ),
    ]
