# Generated by Django 6.0.3 on 2026-05-13 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euser', '0004_alter_mycourse_status_comment_refund_refundprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值金额')),
                ('give_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='送金额')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间')),
                ('tcount', models.IntegerField(default=0, verbose_name='总数量')),
                ('count', models.IntegerField(default=0, verbose_name='领取数量')),
            ],
            options={
                'verbose_name': '充值活动',
                'verbose_name_plural': '充值活动',
                'db_table': 'recharge_activity',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额')),
                ('recharge_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='充值日期')),
                ('pay_type', models.IntegerField(choices=[(1, '支付宝'), (2, '微信')], default=1, verbose_name='支付方式')),
                ('is_give', models.BooleanField(default=False, verbose_name='是否送')),
                ('give_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='送金额')),
                ('recharge_no', models.CharField(default='', max_length=100, verbose_name='流水号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_record', to='euser.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'recharge_record',
                'ordering': ['-id'],
            },
        ),
    ]
